/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange an API key for a bearer token
         * @description The only unauthenticated route.  A bad key is a 401 with no hint
         *     about *which* key -- the response is identical for every failure so
         *     the endpoint cannot be used to probe configured owners.
         */
        post: operations["issue_token_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List jobs for the authenticated owner */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        /** Submit a transit search job */
        post: operations["submit_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a running job */
        post: operations["cancel_job_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the AnalysisResult and provenance for a completed job */
        get: operations["get_result_jobs__job_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream job events (SSE) */
        get: operations["stream_events_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the array artifacts a job holds
         * @description Manifest of servable arrays.  A job with no result yet returns
         *     its dataset (when stored) and an empty candidate list -- 200, not
         *     404.  URLs are templated server-side; the client must never build
         *     a store path.
         */
        get: operations["list_artifacts_jobs__job_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/artifacts/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch decimated array data for charts
         * @description Decimated series for charts.  Refs resolve from the job's own
         *     records -- the request carries no path, so there is nothing to
         *     traverse.  ``If-None-Match`` revalidates against the content ETag
         *     (304).  ``format=npy`` returns a real ``.npy`` payload for
         *     downloads, never raw bytes.
         */
        get: operations["artifact_data_jobs__job_id__artifacts_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copilot/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream an evidence-grounded explanation (AI-INTERPRETED) */
        post: operations["explain_copilot_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactLink */
        ArtifactLink: {
            ref?: components["schemas"]["ArtifactRefOut"] | null;
            /** Url */
            url?: string | null;
        };
        /** ArtifactManifestResponse */
        ArtifactManifestResponse: {
            /** Job Id */
            job_id: string;
            dataset?: components["schemas"]["DatasetManifest"];
            /** Candidates */
            candidates?: components["schemas"]["CandidateArtifactEntry"][];
        };
        /**
         * ArtifactRefOut
         * @description Public projection of ``contracts.dataset.ArtifactRef``.
         *
         *     ``path`` is store-relative and informational only: the client must
         *     use the templated ``url`` from the manifest, never build a path.
         */
        ArtifactRefOut: {
            /** Store */
            store: string;
            /** Path */
            path: string;
            /** Dtype */
            dtype: string;
            /** Shape */
            shape: number[];
            /** Checksum */
            checksum: string;
            /** N Bytes */
            n_bytes: number;
        };
        /** CandidateArtifactEntry */
        CandidateArtifactEntry: {
            /** Candidate Id */
            candidate_id: string;
            /** Period Days */
            period_days?: number | null;
            periodogram?: components["schemas"]["ArtifactLink"];
            folded?: components["schemas"]["ArtifactLink"];
            ttv?: components["schemas"]["TtvManifest"];
        };
        /**
         * CopilotRequest
         * @description Explain this result. ``provider`` overrides the server default.
         */
        CopilotRequest: {
            /**
             * Result
             * @description AnalysisResult dict to explain
             */
            result: {
                [key: string]: unknown;
            };
            /**
             * Question
             * @default Explain these transit-search results for a non-expert.
             */
            question: string;
            /**
             * Provider
             * @description openai | anthropic | google | ollama; null = server default
             */
            provider?: string | null;
        };
        /** DatasetManifest */
        DatasetManifest: {
            /** Dataset Id */
            dataset_id?: string | null;
            ref?: components["schemas"]["ArtifactRefOut"] | null;
            /** Url */
            url?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
            /** Error Kind */
            error_kind?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InlineDataset
         * @description Arrays supplied directly (offline/test path).
         *
         *     Flux errors may be absent; the ``Dataset`` contract reads a missing or
         *     all-zero error column as *absent* rather than trusting it (PRD §5),
         *     so absence is represented as ``None`` on the wire.
         */
        InlineDataset: {
            /** Time */
            time: number[];
            /** Flux */
            flux: number[];
            /** Flux Err */
            flux_err?: number[] | null;
            /** Target Name */
            target_name: string;
        };
        /** JobListResponse */
        JobListResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobResponse"][];
            /** Count */
            count: number;
        };
        /**
         * JobResponse
         * @description The public job row.  Never leaks filesystem paths.
         */
        JobResponse: {
            /** Job Id */
            job_id: string;
            /** Owner Id */
            owner_id: string;
            /** Target Name */
            target_name: string;
            /** Mission */
            mission?: string | null;
            /** Status */
            status: string;
            /** Stage */
            stage: string;
            /** Progress */
            progress: number;
            /** Iteration */
            iteration?: number | null;
            /** Max Iterations */
            max_iterations?: number | null;
            /** N Candidates */
            n_candidates?: number | null;
            /** Result Id */
            result_id?: string | null;
            /** Error */
            error?: string | null;
            /** Error Kind */
            error_kind?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * JobSubmission
         * @description Submit a search job.
         *
         *     Exactly one of ``dataset`` (inline arrays) or ``target`` (fetch real
         *     data) must be supplied -- the PRD's "one Job consumes one Dataset".
         */
        JobSubmission: {
            dataset?: components["schemas"]["InlineDataset"] | null;
            target?: components["schemas"]["TargetDataset"] | null;
            /**
             * Max Signals
             * @default 5
             */
            max_signals: number;
            /**
             * Snr Floor
             * @default 7.1
             */
            snr_floor: number;
        };
        /**
         * ResultResponse
         * @description An ``AnalysisResult`` with its provenance attached (PRD §5/§7).
         *
         *     Every API result must carry provenance; omitting it would force the
         *     client to guess what produced the numbers.
         */
        ResultResponse: {
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * TargetDataset
         * @description Fetch a real light curve through the ingestion seam (P1-D/P1-G).
         */
        TargetDataset: {
            /** Name */
            name: string;
            /**
             * Mission
             * @default Kepler
             */
            mission: string;
        };
        /** TokenRequest */
        TokenRequest: {
            /**
             * Api Key
             * @description The configured API key
             */
            api_key: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /** Owner Id */
            owner_id: string;
            /** Expires In */
            expires_in: number;
        };
        /** TtvManifest */
        TtvManifest: {
            /** N Epochs */
            n_epochs?: number | null;
            /** Rms Minutes */
            rms_minutes?: number | null;
            /** Url */
            url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    issue_token_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_jobs__job_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_jobs__job_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactManifestResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifact_data_jobs__job_id__artifacts_data_get: {
        parameters: {
            query: {
                type: "dataset" | "periodogram" | "folded" | "ttv";
                candidate?: string;
                format?: "json" | "npy";
                max_points?: number;
                stride?: number | null;
                bins?: number;
                t_min?: number | null;
                t_max?: number | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/octet-stream": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_copilot_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopilotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
