"""Shared constants for ASTRAEUS core physics models."""

from __future__ import annotations

import numpy as np
from astropy import units as u

BOUND_ECCENTRICITY_MINIMUM = 0.0
BOUND_ECCENTRICITY_MAXIMUM = 1.0
HIGH_ECCENTRICITY_INITIAL_GUESS_THRESHOLD = 0.8
POSITIVE_QUANTITY_MINIMUM = 0.0

KEPLER_NEWTON_TOLERANCE = 1.0e-12
KEPLER_NEWTON_MAX_ITERATIONS = 64

HALF_TURN_ANGLE = np.pi * u.rad
HALF_TURNS_PER_FULL_TURN = 2.0
FULL_TURN_ANGLE = HALF_TURNS_PER_FULL_TURN * HALF_TURN_ANGLE

REFERENCE_LENGTH_UNIT = u.AU
